### ISSUE TITLE
Just for fun: How long would training this model take on a Nvidia 1080Ti GPU (12gb)

### ISSUE THREAD

**Issue by timpal0l** [salesforce/ctrl#44]
It says in the paper they used 256 cores of Cloud TPU V3. Is it possible to estimate by any means?
a year?

**Comment by keskarnitish** [comment]
That's a difficult question to answer because of the number of variables involved (batch size, effect of `bsz` on convergence, TPU vs GPU, memory size etc.). But, [this guide](https://timdettmers.com/2018/10/17/tpus-vs-gpus-for-transformers-bert/) would be a great starting point for such comparisons.
