### ISSUE TITLE
training_utils on new vocab and codes

### ISSUE THREAD

**Issue by ctoffo** [salesforce/ctrl#53]
Hi ! 

Does it make sense to run `make_tf_records.py` and `training.py` on a completely new `vocab` and `codes` made by fastBPE using french texts, without using your `vocab` and `codes` ?
If it does, how ?

Thanks a lot for your help ! :)

**Comment by keskarnitish** [comment]
No, unfortunately you can't do that. Because everything was trained with a specific tokenization, completely changing that won't quite work. Perhaps if you train it long enough, it might produce reasonable results but I wouldn't recommend it. Stepping back, why do you want to do that though? There are french tokens as a part of the BPE (AFAIK), we even have English to French translation capability by using the appropriate control code.
