### ISSUE TITLE
What's the main practical difference between 256 and 512 models?

### ISSUE THREAD

**Issue by dimitri320** [salesforce/ctrl#54]
There are two models available: gs://sf-ctrl/seqlen256_v1.ckpt/ or gs://sf-ctrl/seqlen512_v1.ckpt/

What is the fundamental difference between the two?

**Comment by keskarnitish** [comment]
Only difference is the sequence length used during training. The `512` model uses double the number of tokens as the `256` one for computing the attention but half the batch size (to prevent OOM). Since we are operating at (almost) word level, `256` is plenty. You can always generate past this by sliding windows over. 

Please reopen if this doesn't solve the question.
